### ISSUE TITLE
Refactor: 서버 API 변경 사항 작업

### ISSUE THREAD

**Issue by CLOUDoort** [JECT-Study/Chzz-Market-Frontend#225]
## 구현 기능

서버 API 변경 사항 확인하고 프론트에 적용

## 상세 작업 내용

- [x] 베스트 경매 조회
- [x] 마감 임박 경매 조회
- [x] 사전 경매 조회
- [x] 경매 상세 조회
- [x] 사전 경매 상세 조회
- [x] 입찰 조회
- [x] 찜한 경매 목록 조회
- [x] 사전 경매 수정
- [x] 사전 경매 삭제
- [x] 경매 등록
- [x] 사전 경매 전환
- [x] 사전 경매 찜 요청 및 취소
- [x] 테스트 등록

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Updated API endpoints and response handling for various auction-related operations to align with server API changes.

You can review changes in this commit: https://github.com/lkilu6456546/JECT-Study-Chzz-Market-Frontend-225/commit/607bfe84a49d9bbf8cc6759a3c317f7e51a8115e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
